In [2]:
import pandas as pd
import numpy as np

In [3]:
data = pd.read_csv('ind.csv')

In [4]:
data

,Player,Matches,Innings,Not Outs,Runs,Highest Score,Average,Balls Faced,Strike Rate,100,50,0,4s,6s
0,V Kohli,75,70,20,2633,94*,52.66,1907,138.07,0,24,2,247,71
1,RG Sharma,104,96,14,2633,118,32.10,1905,138.21,4,19,6,234,120
2,MS Dhoni,98,85,42,1617,56,37.60,1282,126.13,0,2,1,116,52
3,SK Raina,78,66,11,1605,101,29.18,1190,134.87,1,5,3,145,58
4,S Dhawan,58,57,3,1504,92,27.85,1173,128.21,0,9,1,166,46
5,Yuvraj Singh,58,51,9,1177,77*,28.02,863,136.38,0,8,1,77,74
6,KL Rahul,34,31,5,1138,110*,43.76,777,146.46,2,8,1,102,50
7,G Gambhir,37,36,2,932,75,27.41,783,119.02,0,7,2,109,10
8,MK Pandey,32,27,12,587,79*,39.13,478,122.80,0,2,2,40,16
9,RR Pant,26,24,4,409,65*,20.45,336,121.72,0,2,3,28,18
10,V Sehwag,19,18,0,394,68,21.88,271,145.38,0,2,1,43,16
11,AM Rahane,20,20,2,375,61,20.83,331,113.29,0,1,2,32,6
12,HH Pandya,40,25,6,310,33*,16.31,210,147.61,0,0,2,18,19
13,RV Uthappa,13,12,2,249,50,24.90,211,118.00,0,1,1,26,6
14,YK Pathan,22,18,5,236,37*,18.15,161,146.58,0,0,3,11,17
15,SS Iyer,14,13,3,226,62,22.60,178,126.96,0,1,1,18,9
16,IK Pathan,24,14,7,172,33*,24.57,144,119.44,0,0,0,9,7
17,M Vijay,9,9,0,169,48,18.77,154,109.74,0,0,1,13,8
18,RA Jadeja,46,22,8,163,25,11.64,165,98.78,0,0,2,7,4
19,R Ashwin,46,11,7,123,31*,30.75,115,106.95,0,0,0,14,1
20,KM Jadhav,9,6,0,122,58,20.33,99,123.23,0,1,0,12,3
21,KH Pandya,18,9,4,121,26*,24.20,92,131.52,0,0,0,8,6